# -*- coding: utf-8 -*-
"""breastCancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgJopzgP8ixo-y7ViDGc2EEZc10V7lP6

## Problem Type

This is a **supervised learning, binary classification** problem.

- **Supervised:** each patient already has a known diagnosis, so the model learns from labeled examples.
- **Classification:** the model predicts a category (malignant or benign), not a number.
- **Binary:** there are only two classes: 1 = malignant, 0 = benign.

**Goal:** use 30 measurements of cell nuclei from a breast tissue sample to predict whether a tumor is malignant or benign.

# Breast Cancer Diagnosis with Machine Learning

**Libraries used:**
- `pandas` (`pd`): loads and works with tables of data (DataFrames)
- `numpy` (`np`): fast math on arrays of numbers
- `matplotlib.pyplot` (`plt`): basic plotting
- `seaborn` (`sns`): nicer statistical plots built on matplotlib
- `sklearn` (scikit-learn): the machine learning library
  - `train_test_split`: splits data into training and testing sets
  - `StandardScaler`: puts all features on the same scale
  - `LogisticRegression`, `RandomForestClassifier`: the models
  - `accuracy_score`, `recall_score`, `classification_report`, `ConfusionMatrixDisplay`: measure how well the models do
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Used for stat plots
import seaborn as sns

# used for machine learning: Splitting, scaling, models, and evaluation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, recall_score, classification_report, ConfusionMatrixDisplay

"""## 1. Load the Data

The file `wdbc.data` has **no header row**, so the column names are created manually.

**Variables:**
- `features`: the 10 nucleus measurements (radius, texture, perimeter, etc.)
- `columns`: the full list of 32 column names: `id`, `diagnosis`, then each feature 3 times:
  - `_avg`: average value across all cells in the image
  - `_variation`: standard error, or how much the cells vary
  - `_largest`: average of the 3 largest values, the most abnormal cells
- `df`: the DataFrame (table) holding all the data

**Functions:**
- `pd.read_csv()`: reads the file into a DataFrame
  - `header=None`: tells pandas the first row is data, not column names
  - `names=columns`: uses our list as the column names
- `f'{f}_mean'`: an f-string that builds names like `radius_mean`
- `df.head(10)`: shows the first 10 rows
"""

features = ['radius', 'texture', 'perimeter', 'area', 'smoothness',
            'compactness', 'concavity', 'concave_points', 'symmetry',
            'fractal_dimension']

columns = (['id', 'diagnosis']
           + [f'{f}_avg' for f in features]
           + [f'{f}_variation' for f in features]
           + [f'{f}_largest' for f in features])

df = pd.read_csv('wdbc.data', header=None, names=columns)
df.head(10)

"""## 2. Explore the Data

Check the size and structure of the data before doing anything with it.

**Functions:**
- `df.shape`: (rows, columns), should be `(569, 32)`
- `df.info()`: lists each column, its data type, and how many non-missing values it has
- `print()`: needed because a notebook cell only displays its last line automatically

**What to look for:**
- 569 non-null in every column means no missing data
- `float64` = decimal numbers (the features)
- `object` = text (`diagnosis` is M/B)
- `int64` = whole numbers (`id`)
"""

# Number of rows and columns, then data types and missing values
print(df.shape)
df.info()

"""## 3. Clean the Data

Make sure the data is complete and in a form the model can use.

**Functions:**
- `df.isnull().sum().sum()`: counts all missing values in the whole table
  - `isnull()` marks missing cells as True
  - the first `.sum()` counts per column, the second adds the columns up
- `df.duplicated().sum()`: counts rows that are exact copies
- `df.drop(columns='id', errors='ignore')`: removes the ID column
  - `errors='ignore'` prevents an error if it was already removed
- `df['diagnosis'].map({'M': 1, 'B': 0})`: replaces M with 1 and B with 0
- `dtype == object`: checks the column is still text, so it isn't converted twice

**Why:**
- The `id` is just a label with no medical meaning, so it could confuse the model.
- Models need numbers, not letters. 1 = malignant (cancer), 0 = benign.
- Running the map twice turns every diagnosis into `NaN`. If that happens, reload the data.
"""

# Check for missing values and duplicates
print('Missing values:', df.isnull().sum().sum())
print('Duplicate rows:', df.duplicated().sum())

# Drop the ID because it has no medical meaning
df = df.drop(columns='id', errors='ignore')

# Convert diagnosis to number: 1 = malignant, 0 = benign
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})
df.head()

"""## 4. Visualize the Data

Exploratory Data Analysis (EDA): look at the data to understand it before training a model.

**Variables:**
- `mean_cols`: list of the 10 column names ending in `_avg`
- `corr`: correlation of each feature with the diagnosis
- `fig, axes`: the figure and its grid of subplots

**Functions:**
- `sns.countplot()`: bar chart counting each class (benign vs malignant)
- `plt.subplots(2, 5)`: creates a grid of 2 rows × 5 columns of plots
- `zip(axes.flat, mean_cols)`: pairs each subplot with one column
- `sns.histplot(..., hue='diagnosis', kde=True)`: histogram split by diagnosis, with a smooth curve
- `.corrwith()`: correlation between each feature and the diagnosis
- `.sort_values()`: orders from lowest to highest
- `.plot(kind='barh')`: horizontal bar chart
- `plt.tight_layout()`: stops plots from overlapping
- `plt.show()`: displays the plot

**What to look for:**
- Class balance: about 357 benign and 212 malignant, so slightly imbalanced
- Histograms: little overlap between colors means the feature is a good predictor
- Correlation: values near 1 are strongly linked to cancer, values near 0 are weakly linked
"""

# How many benign vs malignant cases
sns.countplot(x='diagnosis', data=df)
plt.xticks([0,1], ['Benign', 'Malignant'])
plt.title('Benign vs Malignant')
plt.show()

# Compare benign and malignant distributions for each mean feature
avg_cols = [c for c in df.columns if c.endswith('_avg')]

fig, axes = plt.subplots(2, 4, figsize=(20,8))
for ax, col in zip(axes.flat, avg_cols):
  sns.histplot(data=df, x=col, hue='diagnosis', kde=True, ax=ax)
  ax.set_title(col)


plt.tight_layout()
plt.show()


# Which features are most related to the diagnosis
corr = df.drop(columns='diagnosis').corrwith(df['diagnosis']).sort_values()
corr.plot(kind='barh', figsize=(8, 10))
plt.title('Correlation with Malignancy')
plt.show()

"""## 5. Prepare the Data for Machine Learning

Split the data and scale it so the model can learn fairly.

**Variables:**
- `X`: the inputs (all 30 measurements)
- `y`: the target, what we want to predict (diagnosis)
- `X_train`, `y_train`: 80% of patients, used to **teach** the model
- `X_test`, `y_test`: 20% of patients, kept hidden to **test** the model
- `scaler`: the StandardScaler object
- `X_train_s`, `X_test_s`: the scaled versions of the data

**Functions:**
- `train_test_split()`: randomly splits the data
  - `test_size=0.2`: 20% goes to testing
  - `stratify=y`: keeps the same benign/malignant ratio in both sets
  - `random_state=42`: makes the split the same every time it runs
- `scaler.fit_transform(X_train)`: learns the mean and spread from the training data, then scales it
- `scaler.transform(X_test)`: scales the test data using the **training** values

**Why:**
- The test set acts like new patients, so the model must never see it during training.
- Features have very different ranges (area is in the 1000s, smoothness is about 0.1). Scaling gives each feature mean 0 and standard deviation 1, so no feature dominates just because its numbers are bigger.
- The scaler is fit only on training data to avoid **data leakage**, which happens when test information sneaks into training.
"""

# X = the measurements (inputs), y = the diagnosis (what we predict)

X = df.drop(columns='diagnosis')
y = df['diagnosis']

# Hold back 20% of patients to test the model later
X_train, X_test, y_train, y_test = train_test_split(X, y,
            test_size=0.2, random_state=42, stratify=y)

# Put all features on the same scale (fit only on training data)
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

"""## 6. Train the Models

Teach two different models using the training data, then compare them on the test data.

**Variables:**
- `models`: a dictionary with each model's name and the model itself
- `pred`: the model's predictions for the test patients (0 or 1)

**Functions:**
- `LogisticRegression(max_iter=1000)`: a simple model that draws a boundary between the classes. `max_iter` gives it enough steps to finish learning.
- `RandomForestClassifier()`: many decision trees that vote on the answer
- `model.fit(X_train_s, y_train)`: trains the model
- `model.predict(X_test_s)`: predicts the diagnosis for new patients
- `accuracy_score()`: % of all predictions that were correct
- `recall_score()`: % of actual cancers the model caught

**Why recall matters:** missing a cancer (false negative) is much worse than a false alarm.
"""

# train two models and compare them on the test set

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(random_state=42),
}

for name, model in models.items():
  model.fit(X_train_s, y_train)
  pred = model.predict(X_test_s)
  print(f'{name}: accuracy = {accuracy_score(y_test, pred):.3f}, '
          f'recall = {recall_score(y_test, pred):.3f}')

"""## 7. Evaluate the Model

Look at the results of one model in detail.

**Variables:**
- `best`: the model chosen for detailed evaluation

**Functions:**
- `classification_report()`: precision, recall, and F1 for each class
  - **precision**: of the patients predicted malignant, how many really were
  - **recall**: of the patients who really were malignant, how many were caught
  - **F1**: a balance of precision and recall
- `ConfusionMatrixDisplay.from_estimator()`: a grid of correct and wrong predictions
  - top-left = benign correctly predicted
  - bottom-right = malignant correctly predicted
  - bottom-left = **missed cancers** (the worst error)
  - top-right = false alarms
"""

# Detailed results for one model
best = models['Logistic Regression']

print(classification_report(y_test, best.predict(X_test_s),
                            target_names=['Benign', 'Malignant']))

# Confusion matrix: bottom-left = cancers the model missed
ConfusionMatrixDisplay.from_estimator(best, X_test_s, y_test,
                                      display_labels=['Benign', 'Malignant'],
                                      cmap='Blues')

plt.show()

"""## 8. Make Predictions

Use the trained model like a diagnostic tool on patients it has never seen.

### 8.1 Test patients
Compare the model's predictions with the real diagnoses for 10 test patients.

**Variables:**
- `sample`: the first 10 patients from the test set
- `prob`: the model's probability that each patient is malignant (0 to 1)

**Functions:**
- `.iloc[:10]`: selects the first 10 rows
- `scaler.transform()`: scales the patients the same way as the training data
- `predict_proba()`: returns `[chance benign, chance malignant]` for each patient
- `[:, 1]`: keeps only the malignant chance (`:` = all rows, `1` = second column)
- `.map({0: 'Benign', 1: 'Malignant'})`: turns 0/1 into words
- `display()`: shows a table even when it isn't the last line of the cell
- A probability of **0.5 or more** is predicted malignant

### 8.2 New patients from a file
Predict made-up patients stored in `new_patients.csv`.

**Variables:**
- `new_patients`: the table loaded from the CSV file, one row per patient
- `full`: a complete 30-feature table, starting from typical (median) values
- `result`: the patients plus their probability and prediction

**Functions:**
- `%%writefile new_patients.csv`: creates the CSV file from a code cell
- `pd.read_csv(..., index_col='patient')`: loads the file and uses the patient name as the row label
- `predict_patients()`: our helper function
  - `X.median()`: the middle value of each feature, a "typical" patient
  - features missing from the file are filled with the median
  - `full[X.columns]`: puts the columns in the order the model was trained on
  - returns each patient's malignant probability and prediction
"""

# Predict 10 patient the model has never seen

sample = X_test.iloc[:10]
prob = best.predict_proba(scaler.transform(sample))[:, 1]

display(pd.DataFrame({
    'Actual': y_test.iloc[:10].map({0: 'Benign', 1: 'Malignant'}).values,
    'Predicted': ['Malignant' if p >= 0.5 else 'Benign' for p in prob],
    'Malignant probability': prob.round(3),
}))

# Helper: predict

def predict_patients(patients):
  full = pd.DataFrame([X.median()] * len(patients), index=patients.index)
  for col in patients.columns:
    if col in X.columns:
      full[col] = patients[col]

  prob = best.predict_proba(scaler.transform(full[X.columns]))[:, 1]

  result = patients.copy()
  result['malignant probability'] = prob.round(3)
  result['prediction'] = ['Malignant' if p >= 0.5 else 'Benign' for p in prob]
  return result

# Load new patients from the csv file and predict them

new_patients = pd.read_csv('new_patients.csv', index_col='patient')
display(predict_patients(new_patients))

"""### Prediction Results

**Test patients (8.1):**
- The model correctly predicted **9 out of 10** test patients.
- The one error (row 4) was a **false positive**: a benign tumor predicted as malignant, with a probability of 0.509. This is just above the 0.5 cutoff, so the model was very unsure.
- Rows 3 (0.576) and 6 (0.762) were correct, but with less confidence.

**New patients from the file (8.2):**

| Patient | Malignant probability | Prediction |
|---|---|---|
| A | 1.9% | Benign |
| B | 76.7% | Malignant |
| C | 18.1% | Benign |
| D | 0.5% | Benign |

- Larger tumors (`radius`, `perimeter`) with more inward dents (`concave_points`) get a higher malignant probability.
- Patient C has medium values, so the model is less certain, but it still predicts benign.
- Only 4 features were given. The other 26 were filled with typical (median) values.

**Takeaway:** the probability tells us how confident the model is, not just its final answer. Probabilities close to 0 or 1 mean the model is confident, and values near 0.5 mean it is uncertain. Borderline cases (around 0.4–0.6) should be reviewed by a doctor.
"""